# Generated by Django 4.2.23 on 2025-08-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_testimonials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'ordering': ['-created_at']},
        ),
    ]
