# Generated by Django 4.2.23 on 2025-08-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_testimonials_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='needs_approval',
            field=models.BooleanField(default=False),
        ),
    ]
